# Add configuration values here, as shown below.
#
 #FACEBOOK_KEY: "636240506801065"
# pusher_key: 7381a978f7dd7f9a1117
 #FACEBOOK_SECRET: "9ebfe1ab3223eaaab73eb5717248a71e"
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
